# Generated by Django 2.2.4 on 2019-11-26 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matriz', models.CharField(max_length=320)),
                ('determinante', models.BooleanField()),
                ('traco', models.BooleanField()),
                ('transposta', models.BooleanField()),
                ('inversa', models.BooleanField()),
                ('polinomio_caracteristico', models.BooleanField()),
                ('autovalores', models.BooleanField()),
                ('autovetores', models.BooleanField()),
                ('matriz_diagonal', models.BooleanField()),
            ],
        ),
        migrations.RemoveField(
            model_name='employee',
            name='department',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
